services:
  back-end:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/donasbydonation/back-end:local
    platform: linux/amd64
    container_name: back-end
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - develop-environment
    depends_on:
      - database

  database:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - develop-environment
    env_file: .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]

  dbconsole:
    container_name: phpmyadmin
    image: phpmyadmin:5.1.1
    links:
      - "database:db"
    ports:
      - "23306:80"
    depends_on:
      - database
    networks:
      - develop-environment

networks:
  develop-environment:
    name: develop-environment
