version: "3.8"
services:
  server:
    image: boost
    container_name: boost
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  database:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]